<testsuites name="testsuite/testcases/basic/*" time="1m56.889307489s" tests="14" failures="3">
	<testsuite name="testsuite/testcases/basic/*" tests="14" failures="3" errors="0" id="0" time="1m56.889307489s">
		<testcase name="ingress" classname="ingress" time="1m23.901221985s">
			<failure message="test exited before receiving all expected events; [Submitted, IngressInfo] received but [Succeeded] missing for 1 job(s): context canceled: GET request failed: Get &#34;http://nc-4000-armada-01gkscts393ngzsxhfz3m3dy5e-0.personal-anonymous.localhost:80/&#34;: context deadline exceeded"></failure>
			<system-out><![CDATA[test case started ingress: {queue: e2e-test-queue, job set: ingress-NwDExuMLeV45xzdUjyYRXX, timeout: 1m40s, expected: [Submitted, IngressInfo, Succeeded]}
test case ingress failed: test exited before receiving all expected events; [Submitted, IngressInfo] received but [Succeeded] missing for 1 job(s): context canceled: GET request failed: Get "http://nc-4000-armada-01gkscts393ngzsxhfz3m3dy5e-0.personal-anonymous.localhost:80/": context deadline exceeded
]]></system-out>
		</testcase>
		<testcase name="failure_errimagepull" classname="failure_errimagepull" time="1m56.879792923s">
			<system-out><![CDATA[test case started failure_errimagepull: {queue: e2e-test-queue, job set: failure_errimagepull-iXKkuEnC8YC6MsU33WD3WS, timeout: 5m0s, expected: [Submitted, UnableToSchedule, Failed]}
test case failure_errimagepull succeeded
]]></system-out>
		</testcase>
		<testcase name="failure_namespace" classname="failure_namespace" time="1.807557366s">
			<system-out><![CDATA[test case started failure_namespace: {queue: e2e-test-queue, job set: failure_namespace-kmMNv6QdWdsPGevPZqi9pH, timeout: 1m40s, expected: [Submitted, Failed]}
test case failure_namespace succeeded
]]></system-out>
		</testcase>
		<testcase name="submit_1x1" classname="submit_1x1" time="10.819862894s">
			<system-out><![CDATA[test case started submit_1x1: {queue: e2e-test-queue, job set: submit_1x1-bAXyCq7f4ox2GLqZnJY823, timeout: 1m40s, expected: [Submitted, Succeeded]}
test case submit_1x1 succeeded
]]></system-out>
		</testcase>
		<testcase name="submit_2x3" classname="submit_2x3" time="27.829717427s">
			<system-out><![CDATA[test case started submit_2x3: {queue: e2e-test-queue, job set: submit_2x3-buAHEtyyR5YW6rkrkJQdS6, timeout: 1m40s, expected: [Submitted, Succeeded]}
test case submit_2x3 succeeded
]]></system-out>
		</testcase>
		<testcase name="submit_fileshare_1x1" classname="submit_fileshare_1x1" time="9.820617768s">
			<system-out><![CDATA[test case started submit_fileshare_1x1: {queue: e2e-test-queue, job set: submit_fileshare_1x1-p2RVuUsLDX27rrPwLWTtnn, timeout: 1m40s, expected: [Submitted, Succeeded]}
test case submit_fileshare_1x1 succeeded
]]></system-out>
		</testcase>
		<testcase name="priorityclass_default" classname="priorityclass_default" time="8.821208052s">
			<system-out><![CDATA[test case started priorityclass_default: {queue: e2e-test-queue, job set: priorityclass_default-aUH4FEeasWAiS8NELAQhKZ, timeout: 2m10s, expected: [Submitted, Succeeded]}
test case priorityclass_default succeeded
]]></system-out>
		</testcase>
		<testcase name="cancel_by_set_1x1" classname="cancel_by_set_1x1" time="805.907761ms">
			<system-out><![CDATA[test case started cancel_by_set_1x1: {queue: e2e-test-queue, job set: cancel_by_set_1x1-d4SixfhfXvBWesfURyGtUH, timeout: 1m40s, expected: [Submitted, Cancelled]}
test case cancel_by_set_1x1 succeeded
]]></system-out>
		</testcase>
		<testcase name="submit_random_clientid" classname="submit_random_clientid" time="24.830806418s">
			<system-out><![CDATA[test case started submit_random_clientid: {queue: e2e-test-queue, job set: submit_random_clientid-QjTMGxnojWGTnogGnQMgKn, timeout: 3m0s, expected: [Submitted, Succeeded]}
test case submit_random_clientid succeeded
]]></system-out>
		</testcase>
		<testcase name="failure_oom_1x1" classname="failure_oom_1x1" time="10.820687848s">
			<system-out><![CDATA[test case started failure_oom_1x1: {queue: e2e-test-queue, job set: failure_oom_1x1-KreRkXi9iXLK5wT83BWotS, timeout: 2m30s, expected: [Submitted, Failed]}
test case failure_oom_1x1 succeeded
]]></system-out>
		</testcase>
		<testcase name="gang" classname="gang" time="1m40.00234771s">
			<failure message="unexpected event for job 01gkscts371fzya066en5pxhh5: expected event of type *api.EventMessage_Succeeded, but got &amp;EventMessage_Failed{Failed:&amp;JobFailedEvent{JobId:01gkscts371fzya066en5pxhh5,JobSetId:gang-saLQ7kbKsFPUqGjmGr5yZ6,Queue:e2e-test-queue,Created:2022-12-08 17:34:54.938417158 +0000 UTC,ClusterId:Cluster1,Reason:Container sleep failed with exit code 1 because OOMKilled: &#xA;,ExitCodes:map[string]int32{sleep: 1,},KubernetesId:d24f6a88-492e-46af-8378-7e68820ae01d,NodeName:armada-test-worker,PodNumber:0,ContainerStatuses:[]*ContainerStatus{&amp;ContainerStatus{Name:sleep,ExitCode:1,Message:,Reason:OOMKilled,Cause:OOM,},},Cause:OOM,PodName:armada-01gkscts371fzya066en5pxhh5-0,PodNamespace:personal-anonymous,},}: context deadline exceeded"></failure>
			<system-out><![CDATA[test case started gang: {queue: e2e-test-queue, job set: gang-saLQ7kbKsFPUqGjmGr5yZ6, timeout: 1m40s, expected: [Submitted, Succeeded]}
test case gang failed: unexpected event for job 01gkscts371fzya066en5pxhh5: expected event of type *api.EventMessage_Succeeded, but got &EventMessage_Failed{Failed:&JobFailedEvent{JobId:01gkscts371fzya066en5pxhh5,JobSetId:gang-saLQ7kbKsFPUqGjmGr5yZ6,Queue:e2e-test-queue,Created:2022-12-08 17:34:54.938417158 +0000 UTC,ClusterId:Cluster1,Reason:Container sleep failed with exit code 1 because OOMKilled: 
,ExitCodes:map[string]int32{sleep: 1,},KubernetesId:d24f6a88-492e-46af-8378-7e68820ae01d,NodeName:armada-test-worker,PodNumber:0,ContainerStatuses:[]*ContainerStatus{&ContainerStatus{Name:sleep,ExitCode:1,Message:,Reason:OOMKilled,Cause:OOM,},},Cause:OOM,PodName:armada-01gkscts371fzya066en5pxhh5-0,PodNamespace:personal-anonymous,},}: context deadline exceeded
]]></system-out>
		</testcase>
		<testcase name="service_headless" classname="service_headless" time="16.8312974s">
			<failure message="unexpected event for job 01gkscts371fzya066eqn6e3fs: expected event of type *api.EventMessage_Succeeded, but got &amp;EventMessage_Failed{Failed:&amp;JobFailedEvent{JobId:01gkscts371fzya066eqn6e3fs,JobSetId:service_headless-qbEGqtyMo67oqZrGsHVMyd,Queue:e2e-test-queue,Created:2022-12-08 17:34:33.729315431 +0000 UTC,ClusterId:Cluster1,Reason:Container client failed with exit code 137 because OOMKilled: &#xA;,ExitCodes:map[string]int32{client: 137,},KubernetesId:1c6e6783-b86a-41b2-a8c6-46b4f75fefdb,NodeName:armada-test-worker,PodNumber:0,ContainerStatuses:[]*ContainerStatus{&amp;ContainerStatus{Name:client,ExitCode:137,Message:,Reason:OOMKilled,Cause:OOM,},},Cause:OOM,PodName:armada-01gkscts371fzya066eqn6e3fs-0,PodNamespace:personal-anonymous,},}: no jobs active"></failure>
			<system-out><![CDATA[test case started service_headless: {queue: e2e-test-queue, job set: service_headless-qbEGqtyMo67oqZrGsHVMyd, timeout: 1m40s, expected: [Submitted, Succeeded]}
test case service_headless failed: unexpected event for job 01gkscts371fzya066eqn6e3fs: expected event of type *api.EventMessage_Succeeded, but got &EventMessage_Failed{Failed:&JobFailedEvent{JobId:01gkscts371fzya066eqn6e3fs,JobSetId:service_headless-qbEGqtyMo67oqZrGsHVMyd,Queue:e2e-test-queue,Created:2022-12-08 17:34:33.729315431 +0000 UTC,ClusterId:Cluster1,Reason:Container client failed with exit code 137 because OOMKilled: 
,ExitCodes:map[string]int32{client: 137,},KubernetesId:1c6e6783-b86a-41b2-a8c6-46b4f75fefdb,NodeName:armada-test-worker,PodNumber:0,ContainerStatuses:[]*ContainerStatus{&ContainerStatus{Name:client,ExitCode:137,Message:,Reason:OOMKilled,Cause:OOM,},},Cause:OOM,PodName:armada-01gkscts371fzya066eqn6e3fs-0,PodNamespace:personal-anonymous,},}: no jobs active
]]></system-out>
		</testcase>
		<testcase name="cancel_by_id_1x1" classname="cancel_by_id_1x1" time="805.308721ms">
			<system-out><![CDATA[test case started cancel_by_id_1x1: {queue: e2e-test-queue, job set: cancel_by_id_1x1-qRjSjLgBZUVJrhhJg5gZr3, timeout: 1m40s, expected: [Submitted, Cancelled]}
test case cancel_by_id_1x1 succeeded
]]></system-out>
		</testcase>
		<testcase name="failure_1x1" classname="failure_1x1" time="11.822306654s">
			<system-out><![CDATA[test case started failure_1x1: {queue: e2e-test-queue, job set: failure_1x1-GBbvDJBxfFJW6Wk8vFuy29, timeout: 1m40s, expected: [Submitted, Failed]}
test case failure_1x1 succeeded
]]></system-out>
		</testcase>
	</testsuite>
</testsuites>